// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TightWiki.Data.EfCore;

#nullable disable

namespace TightWiki.Data.EfCore.SqlServer.Migrations.TightWikiDb
{
    [DbContext(typeof(TightWikiDbContext))]
    [Migration("20260819125355_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.ConfigurationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationGroupId")
                        .HasColumnType("int");

                    b.Property<int>("DataTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationGroupId", "Name")
                        .IsUnique();

                    b.ToTable("ConfigurationEntry", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.ConfigurationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConfigurationGroup", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.CryptoCheck", b =>
                {
                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CryptoCheck", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.DataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("DataType", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MenuItem", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.Theme", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassBranding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassDropdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassNavBar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassNavLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelimitedFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditorTheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Theme", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.VersionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VersionState", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPageRevisions.DeletionMeta", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PageId", "Revision");

                    b.HasIndex("DeletedByUserId");

                    b.ToTable("DeletionMeta", "DeletedPageRevisions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPageRevisions.PageRevision", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataHash")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namespace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageId", "Revision");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("PageRevision", "DeletedPageRevisions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPageRevisions.PageRevisionAttachment", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("PageFileId")
                        .HasColumnType("int");

                    b.Property<int>("FileRevision")
                        .HasColumnType("int");

                    b.Property<int>("PageRevision")
                        .HasColumnType("int");

                    b.HasKey("PageId", "PageFileId", "FileRevision", "PageRevision");

                    b.ToTable("PageRevisionAttachment", "DeletedPageRevisions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.DeletionMeta", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PageId");

                    b.HasIndex("DeletedByUserId");

                    b.ToTable("DeletionMeta", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.Page", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Page", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageComment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PageComment", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageFile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PageFile", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageFileRevision", b =>
                {
                    b.Property<int>("PageFileId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("DataHash")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("PageFileId", "Revision");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("PageFileRevision", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageProcessingInstruction", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PageId", "Instruction");

                    b.ToTable("PageProcessingInstruction", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageRevision", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataHash")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namespace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageId", "Revision");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("PageRevision", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageRevisionAttachment", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("PageFileId")
                        .HasColumnType("int");

                    b.Property<int>("FileRevision")
                        .HasColumnType("int");

                    b.Property<int>("PageRevision")
                        .HasColumnType("int");

                    b.HasKey("PageId", "PageFileId", "FileRevision", "PageRevision");

                    b.ToTable("PageRevisionAttachment", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageTag", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PageId", "Tag");

                    b.ToTable("PageTag", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageToken", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DoubleMetaphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("PageId", "Token");

                    b.ToTable("PageToken", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Emoji.Emoji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Emoji")
                        .IsUnique();

                    b.ToTable("Emoji", "Emoji");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Emoji.EmojiCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmojiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EmojiId", "Category" }, "IX_EmojiCategory")
                        .IsUnique();

                    b.ToTable("EmojiCategory", "Emoji");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Logging.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeverityId")
                        .HasColumnType("int");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeverityId");

                    b.ToTable("Log", "Logging");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Logging.Severity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Severity", "Logging");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.CurrentPageEditor", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UtcDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UTCDate");

                    b.HasKey("PageId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CurrentPageEditors", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.FeatureTemplate", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name", "Type");

                    b.HasIndex("PageId");

                    b.ToTable("FeatureTemplate", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex(new[] { "Name" }, "IX_Page_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Navigation" }, "IX_Page_Navigation")
                        .IsUnique();

                    b.ToTable("Page", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PageId" }, "IX_PageComment_PageId");

                    b.ToTable("PageComment", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PageId", "Name", "Revision" }, "IX_PageFile_PageId_Name_Revision")
                        .IsUnique();

                    b.ToTable("PageFile", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageFileRevision", b =>
                {
                    b.Property<int>("PageFileId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("DataHash")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("PageFileId", "Revision");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("PageFileRevision", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageProcessingInstruction", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PageId", "Instruction");

                    b.ToTable("PageProcessingInstruction", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageReference", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("ReferencesPageNavigation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ReferencesPageId")
                        .HasColumnType("int");

                    b.Property<string>("ReferencesPageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageId", "ReferencesPageNavigation");

                    b.HasIndex("ReferencesPageId");

                    b.ToTable("PageReference", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageRevision", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataHash")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namespace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageId", "Revision");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("PageRevision", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageRevisionAttachment", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("PageFileId")
                        .HasColumnType("int");

                    b.Property<int>("FileRevision")
                        .HasColumnType("int");

                    b.Property<int>("PageRevision")
                        .HasColumnType("int");

                    b.HasKey("PageId", "PageFileId", "FileRevision", "PageRevision");

                    b.HasIndex("PageFileId");

                    b.HasIndex(new[] { "PageId", "PageFileId", "PageRevision" }, "IX_PageRevisionAttachment_PageId_PageFileId_PageRevision")
                        .IsUnique();

                    b.ToTable("PageRevisionAttachment", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageTag", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("PageId", "Tag");

                    b.ToTable("PageTag", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageToken", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DoubleMetaphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("PageId", "Token");

                    b.HasIndex(new[] { "DoubleMetaphone", "PageId", "Weight" }, "idx_PageToken_DoubleMetaphone_PageId_Weight");

                    b.HasIndex(new[] { "PageId" }, "idx_PageToken_PageId");

                    b.HasIndex(new[] { "Token", "PageId", "Weight" }, "idx_PageToken_Token_PageId_Weight");

                    b.ToTable("PageToken", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Statistics.PageStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LastBodySize")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastCompileDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastErrorCount")
                        .HasColumnType("int");

                    b.Property<int?>("LastMatchCount")
                        .HasColumnType("int");

                    b.Property<int?>("LastOutgoingLinkCount")
                        .HasColumnType("int");

                    b.Property<int?>("LastProcessedBodySize")
                        .HasColumnType("int");

                    b.Property<int?>("LastTagCount")
                        .HasColumnType("int");

                    b.Property<double?>("LastWikifyTimeMs")
                        .HasColumnType("float");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("TotalCompilationCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double?>("TotalWikifyTimeMs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PageId" }, "IX_CompilationStatistics_PageId")
                        .IsUnique();

                    b.ToTable("PageStatistics", "Statistics");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.AccountPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Namespace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionDispositionId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionDispositionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountPermission", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.AccountRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("AccountRole", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.AdminPwCheck", b =>
                {
                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.ToTable("AdminPwCheck", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permission", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.PermissionDisposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermissionDisposition", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AvatarContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Navigation")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("AccountName")
                        .IsUnique()
                        .HasFilter("[AccountName] IS NOT NULL");

                    b.HasIndex("Navigation")
                        .IsUnique()
                        .HasFilter("[Navigation] IS NOT NULL");

                    b.HasIndex(new[] { "UserId", "AccountName" }, "idx_Profile_UserId_AccountName");

                    b.ToTable("Profile", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBuiltIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Role_Name")
                        .IsUnique();

                    b.ToTable("Role", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Namespace")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionDispositionId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionDispositionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId", "Namespace", "PageId", "PermissionDispositionId")
                        .IsUnique()
                        .HasFilter("[Namespace] IS NOT NULL AND [PageId] IS NOT NULL");

                    b.ToTable("RolePermission", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPageRevisions.DeletionMeta", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "DeletedByUser")
                        .WithMany("DeletedPageRevisions_DeletionMetas")
                        .HasForeignKey("DeletedByUserId");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPageRevisions.PageRevision", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "ModifiedByUser")
                        .WithMany("DeletedPageRevisions_PageRevisions")
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.DeletionMeta", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "DeletedByUser")
                        .WithMany("DeletedPages_DeletionMetas")
                        .HasForeignKey("DeletedByUserId");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.Page", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "CreatedByUser")
                        .WithMany("DeletedPages_CreatedPages")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "ModifiedByUser")
                        .WithMany("DeletedPages_ModifiedPages")
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageComment", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "User")
                        .WithMany("DeletedPages_PageComments")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageFileRevision", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "CreatedByUser")
                        .WithMany("DeletedPages_PageFileRevisions")
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageRevision", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "ModifiedByUser")
                        .WithMany("DeletedPages_PageRevisions")
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Logging.Log", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Logging.Severity", "Severity")
                        .WithMany("Logs")
                        .HasForeignKey("SeverityId");

                    b.Navigation("Severity");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.CurrentPageEditor", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "User")
                        .WithMany("Pages_CurrentPageEditors")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.FeatureTemplate", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("FeatureTemplates")
                        .HasForeignKey("PageId");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.Page", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "CreatedByUser")
                        .WithMany("Pages_CreatedPages")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "ModifiedByUser")
                        .WithMany("Pages_ModifiedPages")
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageComment", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageComments")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "User")
                        .WithMany("Pages_PageComments")
                        .HasForeignKey("UserId");

                    b.Navigation("Page");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageFile", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageFiles")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageFileRevision", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "CreatedByUser")
                        .WithMany("Pages_PageFileRevisions")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.PageFile", "PageFile")
                        .WithMany("PageFileRevisions")
                        .HasForeignKey("PageFileId")
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("PageFile");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageProcessingInstruction", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageProcessingInstructions")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageReference", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageReferencePages")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "ReferencesPage")
                        .WithMany("PageReferenceReferencesPages")
                        .HasForeignKey("ReferencesPageId");

                    b.Navigation("Page");

                    b.Navigation("ReferencesPage");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageRevision", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "ModifiedByUser")
                        .WithMany("Pages_PageRevisions")
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageRevisionAttachment", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.PageFile", "PageFile")
                        .WithMany("PageRevisionAttachments")
                        .HasForeignKey("PageFileId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageRevisionAttachments")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("PageFile");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageTag", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageTags")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageToken", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageTokens")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Statistics.PageStatistic", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithOne("PageStatistic")
                        .HasForeignKey("TightWiki.Data.EfCore.Entities.Statistics.PageStatistic", "PageId")
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.AccountPermission", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.PermissionDisposition", "PermissionDisposition")
                        .WithMany("AccountPermissions")
                        .HasForeignKey("PermissionDispositionId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Permission", "Permission")
                        .WithMany("AccountPermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "Profile")
                        .WithMany("AccountPermissions")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("PermissionDisposition");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.AccountRole", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "Profile")
                        .WithMany("AccountRoles")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.RolePermission", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.PermissionDisposition", "PermissionDisposition")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionDispositionId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("PermissionDisposition");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Logging.Severity", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.Page", b =>
                {
                    b.Navigation("FeatureTemplates");

                    b.Navigation("PageComments");

                    b.Navigation("PageFiles");

                    b.Navigation("PageProcessingInstructions");

                    b.Navigation("PageReferencePages");

                    b.Navigation("PageReferenceReferencesPages");

                    b.Navigation("PageRevisionAttachments");

                    b.Navigation("PageStatistic");

                    b.Navigation("PageTags");

                    b.Navigation("PageTokens");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageFile", b =>
                {
                    b.Navigation("PageFileRevisions");

                    b.Navigation("PageRevisionAttachments");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Permission", b =>
                {
                    b.Navigation("AccountPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.PermissionDisposition", b =>
                {
                    b.Navigation("AccountPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Profile", b =>
                {
                    b.Navigation("AccountPermissions");

                    b.Navigation("AccountRoles");

                    b.Navigation("DeletedPageRevisions_DeletionMetas");

                    b.Navigation("DeletedPageRevisions_PageRevisions");

                    b.Navigation("DeletedPages_CreatedPages");

                    b.Navigation("DeletedPages_DeletionMetas");

                    b.Navigation("DeletedPages_ModifiedPages");

                    b.Navigation("DeletedPages_PageComments");

                    b.Navigation("DeletedPages_PageFileRevisions");

                    b.Navigation("DeletedPages_PageRevisions");

                    b.Navigation("Pages_CreatedPages");

                    b.Navigation("Pages_CurrentPageEditors");

                    b.Navigation("Pages_ModifiedPages");

                    b.Navigation("Pages_PageComments");

                    b.Navigation("Pages_PageFileRevisions");

                    b.Navigation("Pages_PageRevisions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Role", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
