// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TightWiki.Data.EfCore;

#nullable disable

namespace TightWiki.Data.EfCore.Postgres.Migrations.TightWikiDb
{
    [DbContext(typeof(TightWikiDbContext))]
    [Migration("20260821111130_SeedRolePermissionDefaults")]
    partial class SeedRolePermissionDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.ConfigurationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("DataTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("citext");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationGroupId", "Name")
                        .IsUnique();

                    b.ToTable("ConfigurationEntry", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.ConfigurationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("citext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConfigurationGroup", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.CryptoCheck", b =>
                {
                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.ToTable("CryptoCheck", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.DataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataType", "Config");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Integer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "String"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Boolean"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Decimal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Text"
                        });
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MenuItem", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.Theme", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ClassBranding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassDropdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassNavBar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassNavLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DelimitedFiles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EditorTheme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Theme", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Config.VersionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VersionState", "Config");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPageRevisions.DeletionMeta", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PageId", "Revision");

                    b.HasIndex("DeletedByUserId");

                    b.ToTable("DeletionMeta", "DeletedPageRevisions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPageRevisions.PageRevision", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text");

                    b.Property<int>("DataHash")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Namespace")
                        .HasColumnType("citext");

                    b.HasKey("PageId", "Revision");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("PageRevision", "DeletedPageRevisions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPageRevisions.PageRevisionAttachment", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("PageFileId")
                        .HasColumnType("integer");

                    b.Property<int>("FileRevision")
                        .HasColumnType("integer");

                    b.Property<int>("PageRevision")
                        .HasColumnType("integer");

                    b.HasKey("PageId", "PageFileId", "FileRevision", "PageRevision");

                    b.ToTable("PageRevisionAttachment", "DeletedPageRevisions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.DeletionMeta", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PageId")
                        .HasName("PK_DeletionMeta1");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("IX_DeletionMeta_DeletedByUserId1");

                    b.ToTable("DeletionMeta", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.Page", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("Page", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageComment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PageComment", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageFile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PageFile", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageFileRevision", b =>
                {
                    b.Property<int>("PageFileId")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("DataHash")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("PageFileId", "Revision");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("PageFileRevision", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageProcessingInstruction", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("Instruction")
                        .HasColumnType("citext");

                    b.HasKey("PageId", "Instruction");

                    b.ToTable("PageProcessingInstruction", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageRevision", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text");

                    b.Property<int>("DataHash")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Namespace")
                        .HasColumnType("citext");

                    b.HasKey("PageId", "Revision")
                        .HasName("PK_PageRevision1");

                    b.HasIndex("ModifiedByUserId")
                        .HasDatabaseName("IX_PageRevision_ModifiedByUserId1");

                    b.ToTable("PageRevision", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageRevisionAttachment", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("PageFileId")
                        .HasColumnType("integer");

                    b.Property<int>("FileRevision")
                        .HasColumnType("integer");

                    b.Property<int>("PageRevision")
                        .HasColumnType("integer");

                    b.HasKey("PageId", "PageFileId", "FileRevision", "PageRevision")
                        .HasName("PK_PageRevisionAttachment1");

                    b.ToTable("PageRevisionAttachment", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageTag", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .HasColumnType("citext");

                    b.HasKey("PageId", "Tag");

                    b.ToTable("PageTag", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageToken", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("citext");

                    b.Property<string>("DoubleMetaphone")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("PageId", "Token");

                    b.ToTable("PageToken", "DeletedPages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Emoji.Emoji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("MimeType")
                        .HasColumnType("citext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Emoji")
                        .IsUnique();

                    b.ToTable("Emoji", "Emoji");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Emoji.EmojiCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("EmojiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EmojiId", "Category" }, "IX_EmojiCategory")
                        .IsUnique();

                    b.ToTable("EmojiCategory", "Emoji");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Logging.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExceptionText")
                        .HasColumnType("text");

                    b.Property<int?>("SeverityId")
                        .HasColumnType("integer");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeverityId");

                    b.ToTable("Log", "Logging");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Logging.Severity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Severity", "Logging");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Trace"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Debug"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Information"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Warning"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Error"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Critical"
                        },
                        new
                        {
                            Id = 7,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.CurrentPageEditor", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UtcDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UTCDate");

                    b.HasKey("PageId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CurrentPageEditors", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.FeatureTemplate", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("citext");

                    b.Property<string>("Type")
                        .HasColumnType("citext");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateText")
                        .HasColumnType("text");

                    b.HasKey("Name", "Type");

                    b.HasIndex("PageId");

                    b.ToTable("FeatureTemplate", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_Page1");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Page_CreatedByUserId1");

                    b.HasIndex("ModifiedByUserId")
                        .HasDatabaseName("IX_Page_ModifiedByUserId1");

                    b.HasIndex(new[] { "Name" }, "IX_Page_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Navigation" }, "IX_Page_Navigation")
                        .IsUnique();

                    b.ToTable("Page", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_PageComment1");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PageComment_UserId1");

                    b.HasIndex(new[] { "PageId" }, "IX_PageComment_PageId");

                    b.ToTable("PageComment", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_PageFile1");

                    b.HasIndex(new[] { "PageId", "Name", "Revision" }, "IX_PageFile_PageId_Name_Revision")
                        .IsUnique();

                    b.ToTable("PageFile", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageFileRevision", b =>
                {
                    b.Property<int>("PageFileId")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("DataHash")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("PageFileId", "Revision")
                        .HasName("PK_PageFileRevision1");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_PageFileRevision_CreatedByUserId1");

                    b.ToTable("PageFileRevision", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageProcessingInstruction", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("Instruction")
                        .HasColumnType("citext");

                    b.HasKey("PageId", "Instruction")
                        .HasName("PK_PageProcessingInstruction1");

                    b.ToTable("PageProcessingInstruction", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageReference", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferencesPageNavigation")
                        .HasColumnType("citext");

                    b.Property<int?>("ReferencesPageId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferencesPageName")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("PageId", "ReferencesPageNavigation");

                    b.HasIndex("ReferencesPageId");

                    b.ToTable("PageReference", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageRevision", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text");

                    b.Property<int>("DataHash")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Namespace")
                        .HasColumnType("citext");

                    b.HasKey("PageId", "Revision")
                        .HasName("PK_PageRevision2");

                    b.HasIndex("ModifiedByUserId")
                        .HasDatabaseName("IX_PageRevision_ModifiedByUserId2");

                    b.ToTable("PageRevision", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageRevisionAttachment", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("PageFileId")
                        .HasColumnType("integer");

                    b.Property<int>("FileRevision")
                        .HasColumnType("integer");

                    b.Property<int>("PageRevision")
                        .HasColumnType("integer");

                    b.HasKey("PageId", "PageFileId", "FileRevision", "PageRevision")
                        .HasName("PK_PageRevisionAttachment2");

                    b.HasIndex("PageFileId");

                    b.HasIndex(new[] { "PageId", "PageFileId", "PageRevision" }, "IX_PageRevisionAttachment_PageId_PageFileId_PageRevision")
                        .IsUnique();

                    b.ToTable("PageRevisionAttachment", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageTag", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .HasColumnType("citext");

                    b.Property<string>("Navigation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("");

                    b.HasKey("PageId", "Tag")
                        .HasName("PK_PageTag1");

                    b.ToTable("PageTag", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageToken", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("citext");

                    b.Property<string>("DoubleMetaphone")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("PageId", "Token")
                        .HasName("PK_PageToken1");

                    b.HasIndex(new[] { "DoubleMetaphone", "PageId", "Weight" }, "idx_PageToken_DoubleMetaphone_PageId_Weight");

                    b.HasIndex(new[] { "PageId" }, "idx_PageToken_PageId");

                    b.HasIndex(new[] { "Token", "PageId", "Weight" }, "idx_PageToken_Token_PageId_Weight");

                    b.ToTable("PageToken", "Pages");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Statistics.PageStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LastBodySize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastCompileDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastErrorCount")
                        .HasColumnType("integer");

                    b.Property<int?>("LastMatchCount")
                        .HasColumnType("integer");

                    b.Property<int?>("LastOutgoingLinkCount")
                        .HasColumnType("integer");

                    b.Property<int?>("LastProcessedBodySize")
                        .HasColumnType("integer");

                    b.Property<int?>("LastTagCount")
                        .HasColumnType("integer");

                    b.Property<double?>("LastWikifyTimeMs")
                        .HasColumnType("double precision");

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCompilationCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double?>("TotalWikifyTimeMs")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PageId" }, "IX_CompilationStatistics_PageId")
                        .IsUnique();

                    b.ToTable("PageStatistics", "Statistics");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.AccountPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Namespace")
                        .HasColumnType("text");

                    b.Property<string>("PageId")
                        .HasColumnType("text");

                    b.Property<int>("PermissionDispositionId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionDispositionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountPermission", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.AccountRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("AccountRole", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.AdminPwCheck", b =>
                {
                    b.Property<int?>("Value")
                        .HasColumnType("integer");

                    b.ToTable("AdminPwCheck", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permission", "Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "User or role can create pages.",
                            Name = "Create"
                        },
                        new
                        {
                            Id = 2,
                            Description = "User or role can delete page or within namespace.",
                            Name = "Delete"
                        },
                        new
                        {
                            Id = 3,
                            Description = "User or role can edit page or within namespace.",
                            Name = "Edit"
                        },
                        new
                        {
                            Id = 4,
                            Description = "User or role can moderate page or within namespace, such as editing protected pages and reverting changes.",
                            Name = "Moderate"
                        },
                        new
                        {
                            Id = 5,
                            Description = "User or role can read page or within namespace.",
                            Name = "Read"
                        });
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.PermissionDisposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermissionDisposition", "Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Allow"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Deny"
                        });
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea");

                    b.Property<string>("AvatarContentType")
                        .HasColumnType("text");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Navigation")
                        .HasColumnType("citext");

                    b.HasKey("UserId");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.HasIndex("Navigation")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "AccountName" }, "idx_Profile_UserId_AccountName");

                    b.ToTable("Profile", "Users");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("citext");

                    b.Property<bool>("IsBuiltIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Role_Name")
                        .IsUnique();

                    b.ToTable("Role", "Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrators can do anything. Add, edit, delete, etc.",
                            IsBuiltIn = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Read-only user with a profile.",
                            IsBuiltIn = true,
                            Name = "Member"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Contributor can add and edit unprotected pages.",
                            IsBuiltIn = true,
                            Name = "Contributor"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Moderators can add, edit, and delete pages - including protected pages.",
                            IsBuiltIn = true,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Role applied to users who are not logged in.",
                            IsBuiltIn = true,
                            Name = "Anonymous"
                        });
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Namespace")
                        .HasColumnType("text");

                    b.Property<string>("PageId")
                        .HasColumnType("text");

                    b.Property<int>("PermissionDispositionId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionDispositionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId", "Namespace", "PageId", "PermissionDispositionId")
                        .IsUnique();

                    b.ToTable("RolePermission", "Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 5,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 12,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 5,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 13,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 2,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 16,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 2,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 17,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 3,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 18,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 3,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 19,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 20,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 21,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 5,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 22,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 5,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 23,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 24,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 25,
                            PageId = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 26,
                            Namespace = "*",
                            PermissionDispositionId = 1,
                            PermissionId = 5,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPageRevisions.DeletionMeta", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "DeletedByUser")
                        .WithMany("DeletedPageRevisions_DeletionMetas")
                        .HasForeignKey("DeletedByUserId");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPageRevisions.PageRevision", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "ModifiedByUser")
                        .WithMany("DeletedPageRevisions_PageRevisions")
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.DeletionMeta", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "DeletedByUser")
                        .WithMany("DeletedPages_DeletionMetas")
                        .HasForeignKey("DeletedByUserId");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.Page", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "CreatedByUser")
                        .WithMany("DeletedPages_CreatedPages")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "ModifiedByUser")
                        .WithMany("DeletedPages_ModifiedPages")
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageComment", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "User")
                        .WithMany("DeletedPages_PageComments")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageFileRevision", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "CreatedByUser")
                        .WithMany("DeletedPages_PageFileRevisions")
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.DeletedPages.PageRevision", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "ModifiedByUser")
                        .WithMany("DeletedPages_PageRevisions")
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Logging.Log", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Logging.Severity", "Severity")
                        .WithMany("Logs")
                        .HasForeignKey("SeverityId");

                    b.Navigation("Severity");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.CurrentPageEditor", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "User")
                        .WithMany("Pages_CurrentPageEditors")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.FeatureTemplate", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("FeatureTemplates")
                        .HasForeignKey("PageId");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.Page", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "CreatedByUser")
                        .WithMany("Pages_CreatedPages")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "ModifiedByUser")
                        .WithMany("Pages_ModifiedPages")
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageComment", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageComments")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "User")
                        .WithMany("Pages_PageComments")
                        .HasForeignKey("UserId");

                    b.Navigation("Page");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageFile", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageFiles")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageFileRevision", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "CreatedByUser")
                        .WithMany("Pages_PageFileRevisions")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.PageFile", "PageFile")
                        .WithMany("PageFileRevisions")
                        .HasForeignKey("PageFileId")
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("PageFile");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageProcessingInstruction", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageProcessingInstructions")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageReference", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageReferencePages")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "ReferencesPage")
                        .WithMany("PageReferenceReferencesPages")
                        .HasForeignKey("ReferencesPageId");

                    b.Navigation("Page");

                    b.Navigation("ReferencesPage");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageRevision", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "ModifiedByUser")
                        .WithMany("Pages_PageRevisions")
                        .HasForeignKey("ModifiedByUserId");

                    b.Navigation("ModifiedByUser");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageRevisionAttachment", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.PageFile", "PageFile")
                        .WithMany("PageRevisionAttachments")
                        .HasForeignKey("PageFileId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageRevisionAttachments")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("PageFile");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageTag", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageTags")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageToken", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithMany("PageTokens")
                        .HasForeignKey("PageId")
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Statistics.PageStatistic", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Pages.Page", "Page")
                        .WithOne("PageStatistic")
                        .HasForeignKey("TightWiki.Data.EfCore.Entities.Statistics.PageStatistic", "PageId")
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.AccountPermission", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.PermissionDisposition", "PermissionDisposition")
                        .WithMany("AccountPermissions")
                        .HasForeignKey("PermissionDispositionId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Permission", "Permission")
                        .WithMany("AccountPermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "Profile")
                        .WithMany("AccountPermissions")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("PermissionDisposition");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.AccountRole", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Profile", "Profile")
                        .WithMany("AccountRoles")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.RolePermission", b =>
                {
                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.PermissionDisposition", "PermissionDisposition")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionDispositionId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired();

                    b.HasOne("TightWiki.Data.EfCore.Entities.Users.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("PermissionDisposition");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Logging.Severity", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.Page", b =>
                {
                    b.Navigation("FeatureTemplates");

                    b.Navigation("PageComments");

                    b.Navigation("PageFiles");

                    b.Navigation("PageProcessingInstructions");

                    b.Navigation("PageReferencePages");

                    b.Navigation("PageReferenceReferencesPages");

                    b.Navigation("PageRevisionAttachments");

                    b.Navigation("PageStatistic");

                    b.Navigation("PageTags");

                    b.Navigation("PageTokens");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Pages.PageFile", b =>
                {
                    b.Navigation("PageFileRevisions");

                    b.Navigation("PageRevisionAttachments");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Permission", b =>
                {
                    b.Navigation("AccountPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.PermissionDisposition", b =>
                {
                    b.Navigation("AccountPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Profile", b =>
                {
                    b.Navigation("AccountPermissions");

                    b.Navigation("AccountRoles");

                    b.Navigation("DeletedPageRevisions_DeletionMetas");

                    b.Navigation("DeletedPageRevisions_PageRevisions");

                    b.Navigation("DeletedPages_CreatedPages");

                    b.Navigation("DeletedPages_DeletionMetas");

                    b.Navigation("DeletedPages_ModifiedPages");

                    b.Navigation("DeletedPages_PageComments");

                    b.Navigation("DeletedPages_PageFileRevisions");

                    b.Navigation("DeletedPages_PageRevisions");

                    b.Navigation("Pages_CreatedPages");

                    b.Navigation("Pages_CurrentPageEditors");

                    b.Navigation("Pages_ModifiedPages");

                    b.Navigation("Pages_PageComments");

                    b.Navigation("Pages_PageFileRevisions");

                    b.Navigation("Pages_PageRevisions");
                });

            modelBuilder.Entity("TightWiki.Data.EfCore.Entities.Users.Role", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
