namespace TightWiki.Plugin.Engine
{
    /// <summary>
    /// Represents the result of a plugin operation, including output content and a
    /// collection of instructions for further processing.
    /// </summary>
    public class TwPluginResult
    {
        /// <summary>
        /// Text content generated by the plugin handler or function.
        /// </summary>
        public string Content { get; set; } = string.Empty;

        /// <summary>
        /// Collection of instructions defining how the plugin result should be processed.
        /// </summary>
        public List<TwResultInstruction> Instructions { get; set; } = new();

        /// <summary>
        /// Creates a default instance of <see cref="TwPluginResult"/> with empty content and no instructions.
        /// </summary>
        public TwPluginResult()
        {
        }

        /// <summary>
        /// Creates a text result instance of <see cref="TwPluginResult"/> with the specified content and no instructions.
        /// </summary>
        /// <param name="content"></param>
        public TwPluginResult(string content)
        {
            Content = content;
        }
    }
}
