<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Scripts\GetDefaultConfiguration.sql" />
	  <EmbeddedResource Include="Scripts\GetDefaultThemes.sql" />
	  <EmbeddedResource Include="Scripts\RecreateDefaultConfigurationTable.sql" />
	  <EmbeddedResource Include="Scripts\RecreateDefaultThemesTable.sql" />
	  <EmbeddedResource Include="Scripts\RecreateDefaultWikiPagesTable.sql" />
	  <EmbeddedResource Include="Scripts\RecreateDefaultFeatureTemplatesTable.sql" />
	  <EmbeddedResource Include="Scripts\GetFeatureTemplates.sql" />
	  <EmbeddedResource Include="Scripts\GetDefaultDefaultWikiPages.sql" />
	  <EmbeddedResource Include="Scripts\GetDefaultPageFileAttachments.sql" />
	  <EmbeddedResource Include="Scripts\GetDefaultPageStatistics.sql" />
	  <EmbeddedResource Include="Scripts\GetDefaultAdminProfile.sql" />
	  <EmbeddedResource Include="Scripts\Seed\GetConfigurationGroups.sql" />
	  <EmbeddedResource Include="Scripts\Seed\GetConfigurationEntries.sql" />
	  <EmbeddedResource Include="Scripts\Seed\GetMenuItems.sql" />
	  <EmbeddedResource Include="Scripts\Seed\GetEmoji.sql" />
	  <EmbeddedResource Include="Scripts\Seed\GetEmojiCategories.sql" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NTDLS.SqliteDapperWrapper" Version="1.4.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TightWiki.Plugin\TightWiki.Plugin.csproj" />
	</ItemGroup>
</Project>
