IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[DeleteConfigurationEntryById]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[DeleteConfigurationEntryById] AS'
END
GO


ALTER PROCEDURE [dbo].[DeleteConfigurationEntryById]
(
	@Id Int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	DELETE FROM
		[ConfigurationEntry]
	WHERE
		Id = @Id

END--PROCEDURE