IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[DeleteConfigurationGroupById]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[DeleteConfigurationGroupById] AS'
END
GO


ALTER PROCEDURE [dbo].[DeleteConfigurationGroupById]
(
	@Id Int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	DELETE FROM
		[ConfigurationGroup]
	WHERE
		Id = @Id

END--PROCEDURE