IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[GetAllConfigurationGroup]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[GetAllConfigurationGroup] AS'
END
GO


ALTER PROCEDURE [dbo].[GetAllConfigurationGroup] AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[Name] as [Name],
		[Description] as [Description]
	FROM
		[ConfigurationGroup]

END--PROCEDURE