IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[GetAllPage]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[GetAllPage] AS'
END
GO


ALTER PROCEDURE [dbo].[GetAllPage] AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[Name] as [Name],
		[Navigation] as [Navigation],
		[Description] as [Description],
		[Body] as [Body],
		[CreatedByUserId] as [CreatedByUserId],
		[CreatedDate] as [CreatedDate],
		[ModifiedByUserId] as [ModifiedByUserId],
		[ModifiedDate] as [ModifiedDate]
	FROM
		[Page]

END--PROCEDURE