IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[GetAllUser]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[GetAllUser] AS'
END
GO


ALTER PROCEDURE [dbo].[GetAllUser] AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[EmailAddress] as [EmailAddress],
		[DisplayName] as [DisplayName],
		[PasswordHash] as [PasswordHash]
	FROM
		[User]

END--PROCEDURE