IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[GetAllUserRole]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[GetAllUserRole] AS'
END
GO


ALTER PROCEDURE [dbo].[GetAllUserRole] AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[UserId] as [UserId],
		[RoleId] as [RoleId]
	FROM
		[UserRole]

END--PROCEDURE