IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[GetUserRoleById]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[GetUserRoleById] AS'
END
GO


ALTER PROCEDURE [dbo].[GetUserRoleById]
(
	@Id Int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[UserId] as [UserId],
		[RoleId] as [RoleId]
	FROM
		[UserRole]
	WHERE
		Id = @Id

END--PROCEDURE