IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[InsertConfigurationEntry]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[InsertConfigurationEntry] AS'
END
GO




ALTER PROCEDURE [dbo].[InsertConfigurationEntry]
(
	@ConfigurationGroupId as int,
	@Name as nvarchar (128),
	@Value as nvarchar (255) = NULL,
	@Description as nvarchar (1000) = NULL
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;
	
    /* Generated by AsapWiki-ADODAL-Procedures */

	INSERT INTO [ConfigurationEntry]
	(
		[ConfigurationGroupId],
		[Name],
		[Value],
		[Description]
	)
	VALUES
	(
		@ConfigurationGroupId,
		@Name,
		@Value,
		@Description
	)

    SELECT cast(SCOPE_IDENTITY() as int) as [NewId]

END--PROCEDURE