IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[InsertConfigurationGroup]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[InsertConfigurationGroup] AS'
END
GO




ALTER PROCEDURE [dbo].[InsertConfigurationGroup]
(
	@Name as nvarchar (128),
	@Description as nvarchar (1000) = NULL
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;
	
    /* Generated by AsapWiki-ADODAL-Procedures */

	INSERT INTO [ConfigurationGroup]
	(
		[Name],
		[Description]
	)
	VALUES
	(
		@Name,
		@Description
	)

    SELECT cast(SCOPE_IDENTITY() as int) as [NewId]

END--PROCEDURE