IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[InsertPage]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[InsertPage] AS'
END
GO




ALTER PROCEDURE [dbo].[InsertPage]
(
	@Name as nvarchar (128),
	@Navigation as nvarchar (128),
	@Description as nvarchar (MAX),
	@Body as nvarchar (MAX),
	@CreatedByUserId as int,
	@CreatedDate as datetime,
	@ModifiedByUserId as int,
	@ModifiedDate as datetime
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;
	
    /* Generated by AsapWiki-ADODAL-Procedures */

	INSERT INTO [Page]
	(
		[Name],
		[Navigation],
		[Description],
		[Body],
		[CreatedByUserId],
		[CreatedDate],
		[ModifiedByUserId],
		[ModifiedDate]
	)
	VALUES
	(
		@Name,
		@Navigation,
		@Description,
		@Body,
		@CreatedByUserId,
		@CreatedDate,
		@ModifiedByUserId,
		@ModifiedDate
	)

    SELECT cast(SCOPE_IDENTITY() as int) as [NewId]

END--PROCEDURE