IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[InsertUser]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[InsertUser] AS'
END
GO




ALTER PROCEDURE [dbo].[InsertUser]
(
	@EmailAddress as nvarchar (128),
	@DisplayName as nvarchar (128),
	@PasswordHash as nvarchar (128) = NULL
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;
	
    /* Generated by AsapWiki-ADODAL-Procedures */

	INSERT INTO [User]
	(
		[EmailAddress],
		[DisplayName],
		[PasswordHash]
	)
	VALUES
	(
		@EmailAddress,
		@DisplayName,
		@PasswordHash
	)

    SELECT cast(SCOPE_IDENTITY() as int) as [NewId]

END--PROCEDURE