IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[InsertUserRole]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[InsertUserRole] AS'
END
GO




ALTER PROCEDURE [dbo].[InsertUserRole]
(
	@UserId as int,
	@RoleId as int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;
	
    /* Generated by AsapWiki-ADODAL-Procedures */

	INSERT INTO [UserRole]
	(
		[UserId],
		[RoleId]
	)
	VALUES
	(
		@UserId,
		@RoleId
	)

    SELECT cast(SCOPE_IDENTITY() as int) as [NewId]

END--PROCEDURE