IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[UpdateConfigurationEntryById]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[UpdateConfigurationEntryById] AS'
END
GO




ALTER PROCEDURE [dbo].[UpdateConfigurationEntryById]
(
	@Id as int,
	@ConfigurationGroupId as int,
	@Name as nvarchar (128),
	@Value as nvarchar (255) = NULL,
	@Description as nvarchar (1000) = NULL
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	UPDATE
		[ConfigurationEntry]
	SET
		[ConfigurationGroupId] = @ConfigurationGroupId,
		[Name] = @Name,
		[Value] = @Value,
		[Description] = @Description
	FROM
		[ConfigurationEntry]
	WHERE
		Id = @Id

END--PROCEDURE