IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[UpdatePageById]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[UpdatePageById] AS'
END
GO




ALTER PROCEDURE [dbo].[UpdatePageById]
(
	@Id as int,
	@Name as nvarchar (128),
	@Navigation as nvarchar (128),
	@Description as nvarchar (MAX),
	@Body as nvarchar (MAX),
	@CreatedByUserId as int,
	@CreatedDate as datetime,
	@ModifiedByUserId as int,
	@ModifiedDate as datetime
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	UPDATE
		[Page]
	SET
		[Name] = @Name,
		[Navigation] = @Navigation,
		[Description] = @Description,
		[Body] = @Body,
		[CreatedByUserId] = @CreatedByUserId,
		[CreatedDate] = @CreatedDate,
		[ModifiedByUserId] = @ModifiedByUserId,
		[ModifiedDate] = @ModifiedDate
	FROM
		[Page]
	WHERE
		Id = @Id

END--PROCEDURE