IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[UpdateRoleById]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[UpdateRoleById] AS'
END
GO




ALTER PROCEDURE [dbo].[UpdateRoleById]
(
	@Id as int,
	@Name as nvarchar (128),
	@Description as nvarchar (1000) = NULL
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	UPDATE
		[Role]
	SET
		[Name] = @Name,
		[Description] = @Description
	FROM
		[Role]
	WHERE
		Id = @Id

END--PROCEDURE