IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[UpdateUserById]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[UpdateUserById] AS'
END
GO




ALTER PROCEDURE [dbo].[UpdateUserById]
(
	@Id as int,
	@EmailAddress as nvarchar (128),
	@DisplayName as nvarchar (128),
	@PasswordHash as nvarchar (128) = NULL
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	UPDATE
		[User]
	SET
		[EmailAddress] = @EmailAddress,
		[DisplayName] = @DisplayName,
		[PasswordHash] = @PasswordHash
	FROM
		[User]
	WHERE
		Id = @Id

END--PROCEDURE