IF NOT EXISTS(SELECT TOP 1 1 FROM sys.objects WHERE object_id = object_id('[dbo].[UpdateUserRoleById]'))
BEGIN
    EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[UpdateUserRoleById] AS'
END
GO




ALTER PROCEDURE [dbo].[UpdateUserRoleById]
(
	@Id as int,
	@UserId as int,
	@RoleId as int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	UPDATE
		[UserRole]
	SET
		[UserId] = @UserId,
		[RoleId] = @RoleId
	FROM
		[UserRole]
	WHERE
		Id = @Id

END--PROCEDURE