using System.Globalization;
using System.Runtime.CompilerServices;

namespace TightWiki.Tests
{
    /// <summary>
    /// Forces the ambient culture for the entire test process to en-US, independent of whatever locale the
    /// OS/CI runner happens to have configured.
    ///
    /// The <c>Markup/*.wiki.expected</c> fixtures (generated by TightWiki.Test.CaseGenerator) bake in
    /// culture-sensitive formatting produced by plugin code such as HistoryFunctions.cs/MetadataFunctions.cs
    /// (DateTime.ToShortDateString()/ToShortTimeString()) and MarkupHandlers.cs's upsize handler
    /// ("{fontSize:F1}rem" CSS). That plugin code is intentionally NOT hardcoded to a culture - it's meant to
    /// respect the site's configured/request culture in production - so it falls back to whatever
    /// CultureInfo.CurrentCulture is ambient for the calling thread. In production that's set per-request by
    /// app.UseRequestLocalization; here, since tests call WikiEngine directly, nothing sets it, so it defaults
    /// to whatever culture the OS/CI runner exposes to the process (en-US on windows-latest, invariant/other on
    /// ubuntu-latest, cs-CZ on a Czech dev machine, etc). The expected fixtures were generated with en-US
    /// formatting (e.g. "8/28/2023 7:53 PM"), so the test process needs to pin that same culture regardless of
    /// the host OS/locale.
    ///
    /// A module initializer is used instead of TwEngineFixture's constructor because it's guaranteed by the
    /// runtime to run exactly once, before ANY other code in this assembly executes - including test discovery
    /// and any static/instance state that individual test classes or fixtures set up - regardless of xunit's
    /// parallelization or collection ordering. TwEngineFixture's own double-checked-locking singleton only
    /// covers the first construction of that one fixture; other test classes/fixtures could run before it.
    ///
    /// Both CurrentCulture/CurrentUICulture (ambient for already-running threads, and - since .NET Core -
    /// flows via AsyncLocal across await boundaries, which is what matters since xunit runs tests on the
    /// thread pool, not a single thread) and DefaultThreadCurrentCulture/DefaultThreadCurrentUICulture (the
    /// culture assigned to any NEW thread that doesn't inherit an ambient one) are set, to cover every thread
    /// the test host may end up running plugin code on.
    /// </summary>
    internal static class TestCultureInitializer
    {
        [ModuleInitializer]
        internal static void SetEnUsCulture()
        {
            var enUs = CultureInfo.GetCultureInfo("en-US");

            CultureInfo.CurrentCulture = enUs;
            CultureInfo.CurrentUICulture = enUs;
            CultureInfo.DefaultThreadCurrentCulture = enUs;
            CultureInfo.DefaultThreadCurrentUICulture = enUs;
        }
    }
}
