--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('GetAllMenuItem') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [GetAllMenuItem]
END--IF
GO

CREATE PROCEDURE [GetAllMenuItem] AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[Name] as [Name],
		[Link] as [Link],
		[Ordinal] as [Ordinal]
	FROM
		[MenuItem]

END--PROCEDURE
GO

--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('DeleteMenuItemById') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [DeleteMenuItemById]
END--IF
GO

CREATE PROCEDURE [DeleteMenuItemById]
(
	@Id Int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	DELETE FROM
		[MenuItem]
	WHERE
		Id = @Id

END--PROCEDURE
GO


--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('GetMenuItemById') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [GetMenuItemById]
END--IF
GO

CREATE PROCEDURE [GetMenuItemById]
(
	@Id Int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[Name] as [Name],
		[Link] as [Link],
		[Ordinal] as [Ordinal]
	FROM
		[MenuItem]
	WHERE
		Id = @Id

END--PROCEDURE
GO

--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('UpdateMenuItemById') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [UpdateMenuItemById]
END--IF
GO



CREATE PROCEDURE [UpdateMenuItemById]
(
	@Id as int,
	@Name as nvarchar (128),
	@Link as nvarchar (128),
	@Ordinal as int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	UPDATE
		[MenuItem]
	SET
		[Name] = @Name,
		[Link] = @Link,
		[Ordinal] = @Ordinal
	FROM
		[MenuItem]
	WHERE
		Id = @Id

END--PROCEDURE
GO

--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('InsertMenuItem') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [InsertMenuItem]
END--IF
GO



CREATE PROCEDURE [InsertMenuItem]
(
	@Name as nvarchar (128),
	@Link as nvarchar (128),
	@Ordinal as int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;
	
    /* Generated by AsapWiki-ADODAL-Procedures */

	INSERT INTO [MenuItem]
	(
		[Name],
		[Link],
		[Ordinal]
	)
	VALUES
	(
		@Name,
		@Link,
		@Ordinal
	)

    SELECT cast(SCOPE_IDENTITY() as int) as [NewId]

END--PROCEDURE
GO

