--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('GetAllConfigurationEntry') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [GetAllConfigurationEntry]
END--IF
GO

CREATE PROCEDURE [GetAllConfigurationEntry] AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[ConfigurationGroupId] as [ConfigurationGroupId],
		[Name] as [Name],
		[Value] as [Value]
	FROM
		[ConfigurationEntry]

END--PROCEDURE
GO

--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('DeleteConfigurationEntryById') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [DeleteConfigurationEntryById]
END--IF
GO

CREATE PROCEDURE [DeleteConfigurationEntryById]
(
	@Id Int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	DELETE FROM
		[ConfigurationEntry]
	WHERE
		Id = @Id

END--PROCEDURE
GO


--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('GetConfigurationEntryById') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [GetConfigurationEntryById]
END--IF
GO

CREATE PROCEDURE [GetConfigurationEntryById]
(
	@Id Int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[ConfigurationGroupId] as [ConfigurationGroupId],
		[Name] as [Name],
		[Value] as [Value]
	FROM
		[ConfigurationEntry]
	WHERE
		Id = @Id

END--PROCEDURE
GO

--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('UpdateConfigurationEntryById') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [UpdateConfigurationEntryById]
END--IF
GO



CREATE PROCEDURE [UpdateConfigurationEntryById]
(
	@Id as int,
	@ConfigurationGroupId as int,
	@Name as varchar (128),
	@Value as varchar (255) = NULL
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	UPDATE
		[ConfigurationEntry]
	SET
		[ConfigurationGroupId] = @ConfigurationGroupId,
		[Name] = @Name,
		[Value] = @Value
	FROM
		[ConfigurationEntry]
	WHERE
		Id = @Id

END--PROCEDURE
GO

--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('InsertConfigurationEntry') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [InsertConfigurationEntry]
END--IF
GO



CREATE PROCEDURE [InsertConfigurationEntry]
(
	@ConfigurationGroupId as int,
	@Name as varchar (128),
	@Value as varchar (255) = NULL
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;
	
    /* Generated by AsapWiki-ADODAL-Procedures */

	INSERT INTO [ConfigurationEntry]
	(
		[ConfigurationGroupId],
		[Name],
		[Value]
	)
	VALUES
	(
		@ConfigurationGroupId,
		@Name,
		@Value
	)

    SELECT cast(SCOPE_IDENTITY() as int) as [NewId]

END--PROCEDURE
GO



--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('GetAllConfigurationGroup') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [GetAllConfigurationGroup]
END--IF
GO

CREATE PROCEDURE [GetAllConfigurationGroup] AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[Name] as [Name]
	FROM
		[ConfigurationGroup]

END--PROCEDURE
GO

--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('DeleteConfigurationGroupById') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [DeleteConfigurationGroupById]
END--IF
GO

CREATE PROCEDURE [DeleteConfigurationGroupById]
(
	@Id Int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	DELETE FROM
		[ConfigurationGroup]
	WHERE
		Id = @Id

END--PROCEDURE
GO


--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('GetConfigurationGroupById') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [GetConfigurationGroupById]
END--IF
GO

CREATE PROCEDURE [GetConfigurationGroupById]
(
	@Id Int
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	
	SELECT
		[Id] as [Id],
		[Name] as [Name]
	FROM
		[ConfigurationGroup]
	WHERE
		Id = @Id

END--PROCEDURE
GO

--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('UpdateConfigurationGroupById') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [UpdateConfigurationGroupById]
END--IF
GO



CREATE PROCEDURE [UpdateConfigurationGroupById]
(
	@Id as int,
	@Name as varchar (128)
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;

    /* Generated by AsapWiki-ADODAL-Procedures */
	
	UPDATE
		[ConfigurationGroup]
	SET
		[Name] = @Name
	FROM
		[ConfigurationGroup]
	WHERE
		Id = @Id

END--PROCEDURE
GO

--------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('InsertConfigurationGroup') IS NOT NULL
BEGIN--IF
	DROP PROCEDURE [InsertConfigurationGroup]
END--IF
GO



CREATE PROCEDURE [InsertConfigurationGroup]
(
	@Name as varchar (128)
) AS
BEGIN--PROCEDURE
	SET NOCOUNT ON;
	
    /* Generated by AsapWiki-ADODAL-Procedures */

	INSERT INTO [ConfigurationGroup]
	(
		[Name]
	)
	VALUES
	(
		@Name
	)

    SELECT cast(SCOPE_IDENTITY() as int) as [NewId]

END--PROCEDURE
GO

