--##IF TABLE NOT EXISTS(AccountRole)

CREATE TABLE "AccountRole" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"UserId"	TEXT NOT NULL COLLATE NOCASE,
	"RoleId"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT),
	CONSTRAINT "IX_Unique" UNIQUE("UserId","RoleId"),
	FOREIGN KEY("RoleId") REFERENCES "Role"("Id"),
	FOREIGN KEY("UserId") REFERENCES "Profile"("UserId")
);
