INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Cerulean', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/cerulean/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/cerulean/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Cosmo', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/cosmo/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/cosmo/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Cyborg', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/cyborg/bootstrap.min.css;/css/dark.css;/syntax/styles/dark.css', 'navbar-primary bg-primary', 'text-white', 'text-white', 'text-white', 'dark'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/cyborg/bootstrap.min.css;/css/dark.css;/syntax/styles/dark.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-white', ClassDropdown = 'text-white', ClassBranding = 'text-white', EditorTheme = 'dark';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Flatly', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/flatly/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/flatly/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Journal', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/journal/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/journal/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Light', '/css/light.css;/syntax/styles/light.css', 'navbar-light bg-light', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = '/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-light bg-light', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Litera', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/litera/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/litera/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Lumen', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/lumen/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-light', 'text-dark', 'text-light', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/lumen/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-light', ClassDropdown = 'text-dark', ClassBranding = 'text-light', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Lux', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/lux/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-light', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/lux/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-light', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Materia', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/materia/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/materia/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Minty', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/minty/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/minty/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Morph', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/morph/bootstrap.min.css;/css/gray.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/morph/bootstrap.min.css;/css/gray.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Pulse', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/pulse/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-light', 'text-dark', 'text-light', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/pulse/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-light', ClassDropdown = 'text-dark', ClassBranding = 'text-light', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Quartz', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/quartz/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/quartz/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Sandstone', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/sandstone/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-secondary', 'text-primary', 'text-light', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/sandstone/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-secondary', ClassDropdown = 'text-primary', ClassBranding = 'text-light', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Simplex', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/simplex/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-light', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/simplex/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-light', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Sketchy', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/sketchy/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-light', 'text-dark', 'text-light', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/sketchy/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-light', ClassDropdown = 'text-dark', ClassBranding = 'text-light', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Slate', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/slate/bootstrap.min.css;/css/gray.css;/syntax/styles/dark.css', 'navbar-primary bg-primary', 'text-light', 'text-light', 'text-light', 'dark'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/slate/bootstrap.min.css;/css/gray.css;/syntax/styles/dark.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-light', ClassDropdown = 'text-light', ClassBranding = 'text-light', EditorTheme = 'dark';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Solar', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/solar/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/solar/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Spacelab', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/spacelab/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/spacelab/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Superhero', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/superhero/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/superhero/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'United', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/united/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/united/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Vapor', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/vapor/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/vapor/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Yeti', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/yeti/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/yeti/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Zephyr', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/zephyr/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-primary bg-primary', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/zephyr/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Darkly', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/darkly/bootstrap.min.css;/css/dark.css;/syntax/styles/dark.css', 'navbar-primary bg-primary', 'text-light', 'text-light', 'text-light', 'dark'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/darkly/bootstrap.min.css;/css/dark.css;/syntax/styles/dark.css', ClassNavBar = 'navbar-primary bg-primary', ClassNavLink = 'text-light', ClassDropdown = 'text-light', ClassBranding = 'text-light', EditorTheme = 'dark';
INSERT INTO Theme(Name, DelimitedFiles, ClassNavBar, ClassNavLink, ClassDropdown, ClassBranding, EditorTheme)
SELECT 'Technobabble', 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/brite/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', 'navbar-light bg-light', 'text-dark', 'text-dark', 'text-dark', 'light'
ON CONFLICT(Name) DO UPDATE SET DelimitedFiles = 'https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.7/brite/bootstrap.min.css;/css/light.css;/syntax/styles/light.css', ClassNavBar = 'navbar-light bg-light', ClassNavLink = 'text-dark', ClassDropdown = 'text-dark', ClassBranding = 'text-dark', EditorTheme = 'light';
