DROP TABLE IF EXISTS DefaultPages;

CREATE TABLE DefaultPages (
	Name TEXT NOT NULL COLLATE NOCASE,
	Namespace TEXT NOT NULL COLLATE NOCASE,
	Navigation TEXT NOT NULL COLLATE NOCASE,
	Description TEXT NOT NULL,
	Revision INTEGER NOT NULL,
	DataHash INTEGER NOT NULL,
	Body TEXT NOT NULL
);
